### PR TITLE
add a COMMUNITY_GUIDELINES.md file #10

### PR DESCRIPTION
**Pull request by Bennykillua**
This PR add a markdown file that contains 5 community guidelines that members of the community have to follow. 

It resolves issue #10  @melvincwng

### CODE REVIEW

**Review by melvincwng — CHANGES_REQUESTED** [review]
Hi @Bennykillua, great work!

Just a small request - can you kindly change the name of the document to 'COMMUNITY_GUIDELINES.md' instead?

Basically just make it capitalized.

Thanks, ping me once you've done that!

**Comment by melvincwng** [comment]
@Bennykillua , I have renamed the file on your behalf.

Overall, awesome job! Have added you to the list of contributors :)

Merged your PR, and happy Hacktoberfest 2022 🎉 

Don't forget to follow me and this organization for updates to this project :)

**Review by melvincwng — APPROVED** [review]
LGTM!

**Comment by Bennykillua** [comment]
Thanks @melvincwng

**Pull request merged**
