### PR TITLE
fixed title tag

### PR DESCRIPTION
**Pull request by GabrielWarner**

### CODE REVIEW

**Review by melvincwng — CHANGES_REQUESTED** [review]
@GabrielWarner Hi Gabriel, PR looks good.

But can you add yourself as well in 'contributors.tsx' page? Since I noticed you have React.js experience.

Let me know once you added yourself in 'contributors.tsx' page (just follow the general format which is already there)

**Comment by GabrielWarner** [comment]
ok i will

**Comment by melvincwng** [comment]
Closes #39

**Review by melvincwng — APPROVED** [review]
LGTM!

**Comment by GabrielWarner** [comment]
Sorry, I only put it in the MD file and not the .tsx file. Hopefully I can help out more with this project!

**Comment by melvincwng** [comment]
@GabrielWarner Thanks for your contributions Gabriel!

Don't forget to follow me on GitHub & join our organization over [here](https://github.com/Your-First-Open-Source-Project/Your-First-Open-Source-Project) to stay tuned to future updates on this project!

Happy Hacktoberfest 2022, take care 😄

**Comment by melvincwng** [comment]
@GabrielWarner Stay tuned to our organization for future issues that you can help out for the project :)

**Pull request merged**
