### PR TITLE
second half

### PR DESCRIPTION
**Pull request by GabrielWarner**

### CODE REVIEW

**Review by melvincwng — CHANGES_REQUESTED** [review]
Hi @GabrielWarner, great work! Two issues that need to be fixed before PR is merged:

1. Can you kindly check and ensure there's no duplicate images. There are duplicate images in the PR towards the end.
2. It seems like there are 91 members now in our organization. Can you add the remaining 2 new members as well?

Appreciate the help given, let me know when it's done. Thanks

**Comment by melvincwng** [comment]
Preview mode: https://deploy-preview-56--hacktoberfest2022.netlify.app/community-members

**Comment by melvincwng** [comment]
Closes #6

**Comment by GabrielWarner** [comment]
I found 2 profiles that give me a 404 when I click on them, but they are still in the list counting up to 91.

**Review by flawlesslys — APPROVED** [review]
LGTM

**Review by melvincwng — APPROVED** [review]
Will check the issue regarding the 2 members later.

Meanwhile I approved and merged the PR

**Pull request merged**
